---
apiVersion: v1
kind: Namespace
metadata: 
  name: test
...

"---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-app
  namespace: test
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: httpd
          ports:
            -containerPort: 80
  selector:
    app: my-app
  replicas: 4
..."
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-app
  namespace: test
spec:
  replicas: 3
  selector:
    app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: httpd
          ports:
            - containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: test
spec:
  ports:
    - name: my-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: my-app
  type: NodePort
...
