---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels: 
    app: app-v1
  namespace: test
spec:
  selector:
    matchExpressions:
    - {key: app, operator: In, values: [my-app, cbz-app, app-v1]}
  template:
    meatadata:
      labels:
        app: app-v1
        env: test
        project: Cloudblitz
    spec:
      containers:
        - name: cbz-container
          image: nginx
          ports:
            - containerPort: 8080
  replicas: 10
...